### ISSUE TITLE
Bottom buttons are inaccessible in Firefox Preview

### ISSUE THREAD

**Issue by Bobbbay** [wwebdev/separator-generator#7]
I spotted this on Reddit, this should be solved quick. I don't really have time to add on to [this](https://github.com/wwebdev/separator-generator/blob/master/components/Generator/styled.js), so I think I'll just leave it here for anyobdy to pick up. Happy Hacking!

```HTML
<meta name="viewport" content="viewport-fit=cover" />
```

```CSS
body {
  padding:
    env(safe-area-inset-top, 20px)
    env(safe-area-inset-right, 20px)
    env(safe-area-inset-bottom, 20px)
    env(safe-area-inset-left, 20px);
}
```

See more [here](https://developer.mozilla.org/en-US/docs/Web/CSS/env).

Thanks for your time, Bobbbay
